### ISSUE TITLE
Setup: Kanban project board

### ISSUE THREAD

**Issue by blessedjasonmwanza** [cwaku/spacex-booking#49]
## Setup: Kanban project board
In this project setup update, we're **2 collaborators**. Namely: @blessedjasonmwanza   and  @cwaku 
- Collaborated and guided each other on how to setup /copy [Kanban Board](https://github.com/cwaku/spacex-booking/projects/1)
- Agree and assign tasks to each other following agreed on task allocations

**Comment by elyor-doniyorov** [comment]
Hi @blessedjasonmwanza and @cwaku, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [x] You have submitted a project, that does not have information about the number of people in your group.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by blessedjasonmwanza** [comment]
> Hi @blessedjasonmwanza and @cwaku,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> * [x]  You have submitted a project, that does not have information about the number of people in your group.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray
> 
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Hey @elyor-doniyorov , Thanks a lot for that bug point out 👀  😄 . We worked on it and now on to request for an approval.

> HappyCoding 👨🏽‍💻

**Comment by bimbolabuari** [comment]
# Project Approved 🚀

Hi Team🥇,

Your project is complete! Congratulations! 🎉


Cheers and Happy coding!👏👏👏

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
